{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "addons": {
    "apt": {
      "packages": [
        "doxygen",
        "cppcheck"
      ]
    }
  },
  "before_script": [
    "mkdir build",
    "cd build",
    "cmake ..",
    "cd .."
  ],
  "script": [
    "cppcheck --error-exitcode=1 --enable=warning,style,performance,portability,unusedFunction --verbose -I lib/include app/ lib/",
    "cd build",
    "cmake --build .",
    "cd ..",
    "cd doc",
    "doxygen",
    "make html",
    "cd .."
  ],
  "compiler": "clang",
  "language": "cpp",
}