{
  "os": "linux",
  "dist": "trusty",
  "sudo": false,
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "cmake",
        "doxygen"
      ]
    }
  },
  "script": [
    "cmake . -B\".build\" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug",
    "cmake --build .build --target all"
  ],
  "language": "cpp"
}