{
  "os": "linux",
  "dist": "trusty",
  "sudo": false,
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "ubuntu-toolchain-r-test"
      ],
      "packages": [
        "g++-6",
        "cmake",
        "doxygen",
        "doxygen-doc",
        "doxygen-latex",
        "doxygen-gui",
        "graphviz"
      ]
    }
  },
  "before_install": [
    "pip install --user cpp-coveralls"
  ],
  "script": [
    "CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake . -B\".build\" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCOVERAGE=1",
    "cmake --build .build --target all",
    "./tests",
    "cd .build && ctest -VV"
  ],
  "language": "cpp",
  "global_env": "GH_REPO_NAME=leistungsnachweis-algo DOXYFILE=$TRAVIS_BUILD_DIR/Doxyfile GH_REPO_REF=github.com/ob-algdatii-ss18/leistungsnachweis-algo.git",
  "after_success": [
    "cd $TRAVIS_BUILD_DIR",
    "chmod +x generateDocumentationAndDeploy.sh",
    "./generateDocumentationAndDeploy.sh",
    "cd $TRAVIS_BUILD_DIR",
    "coveralls --exclude googletest --exclude test --exclude .build --exclude code_docs"
  ]
}

