language: cpp
compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..
  - mkdir output

script:
  - cmake --build .
  - ctest .
  - cd ..

after_success:
  - coveralls --exclude build/CMakeFiles/ --exclude build/gtest/ --exclude build/args/ --gcov "llvm-cov gcov" --gcov-options '\-lp'


